// constants.js
export default {
    LANGUAGE_JAPAN: "LANGUAGE_JAPAN",
    LANGUAGE_ENGLISH: "LANGUAGE_ENGLISH",
    LANGUAGE_GERMAN: "LANGUAGE_GERMAN",
    QUIZ_TYPE_A: "QUIZ_TYPE_A",
    QUIZ_TYPE_B: "QUIZ_TYPE_B"
};